from __future__ import annotations

from dataclasses import dataclass, field
from decimal import Decimal
from enum import StrEnum


class SignalTag(StrEnum):
    # --- Fundamental ---
    UNDERVALUED = "UNDERVALUED"
    OVERVALUED = "OVERVALUED"
    FAIRLY_VALUED = "FAIRLY_VALUED"
    DEEP_VALUE = "DEEP_VALUE"
    MOAT_WIDENING = "MOAT_WIDENING"
    MOAT_STABLE = "MOAT_STABLE"
    MOAT_NARROWING = "MOAT_NARROWING"
    NO_MOAT = "NO_MOAT"
    EARNINGS_QUALITY_HIGH = "EARNINGS_QUALITY_HIGH"
    EARNINGS_QUALITY_LOW = "EARNINGS_QUALITY_LOW"
    REVENUE_ACCELERATING = "REVENUE_ACCELERATING"
    REVENUE_DECELERATING = "REVENUE_DECELERATING"
    MARGIN_EXPANDING = "MARGIN_EXPANDING"
    MARGIN_COMPRESSING = "MARGIN_COMPRESSING"
    BALANCE_SHEET_STRONG = "BALANCE_SHEET_STRONG"
    BALANCE_SHEET_WEAK = "BALANCE_SHEET_WEAK"
    DIVIDEND_GROWING = "DIVIDEND_GROWING"
    BUYBACK_ACTIVE = "BUYBACK_ACTIVE"
    MANAGEMENT_ALIGNED = "MANAGEMENT_ALIGNED"

    # --- Macro/Cycle ---
    REGIME_BULL = "REGIME_BULL"
    REGIME_BEAR = "REGIME_BEAR"
    REGIME_NEUTRAL = "REGIME_NEUTRAL"
    REGIME_TRANSITION = "REGIME_TRANSITION"
    SECTOR_ROTATION_INTO = "SECTOR_ROTATION_INTO"
    SECTOR_ROTATION_OUT = "SECTOR_ROTATION_OUT"
    CREDIT_TIGHTENING = "CREDIT_TIGHTENING"
    CREDIT_EASING = "CREDIT_EASING"
    RATE_RISING = "RATE_RISING"
    RATE_FALLING = "RATE_FALLING"
    INFLATION_HIGH = "INFLATION_HIGH"
    INFLATION_LOW = "INFLATION_LOW"
    DOLLAR_STRONG = "DOLLAR_STRONG"
    DOLLAR_WEAK = "DOLLAR_WEAK"
    GEOPOLITICAL_RISK = "GEOPOLITICAL_RISK"
    SUPPLY_CHAIN_DISRUPTION = "SUPPLY_CHAIN_DISRUPTION"
    FISCAL_STIMULUS = "FISCAL_STIMULUS"
    FISCAL_CONTRACTION = "FISCAL_CONTRACTION"
    LIQUIDITY_ABUNDANT = "LIQUIDITY_ABUNDANT"
    LIQUIDITY_TIGHT = "LIQUIDITY_TIGHT"
    REFLEXIVITY_DETECTED = "REFLEXIVITY_DETECTED"

    # --- Technical/Timing ---
    TREND_UPTREND = "TREND_UPTREND"
    TREND_DOWNTREND = "TREND_DOWNTREND"
    TREND_SIDEWAYS = "TREND_SIDEWAYS"
    MOMENTUM_STRONG = "MOMENTUM_STRONG"
    MOMENTUM_WEAK = "MOMENTUM_WEAK"
    MOMENTUM_DIVERGENCE = "MOMENTUM_DIVERGENCE"
    BREAKOUT_CONFIRMED = "BREAKOUT_CONFIRMED"
    BREAKDOWN_CONFIRMED = "BREAKDOWN_CONFIRMED"
    SUPPORT_NEAR = "SUPPORT_NEAR"
    RESISTANCE_NEAR = "RESISTANCE_NEAR"
    VOLUME_SURGE = "VOLUME_SURGE"
    VOLUME_DRY = "VOLUME_DRY"
    VOLUME_CLIMAX = "VOLUME_CLIMAX"
    RSI_OVERSOLD = "RSI_OVERSOLD"
    RSI_OVERBOUGHT = "RSI_OVERBOUGHT"
    GOLDEN_CROSS = "GOLDEN_CROSS"
    DEATH_CROSS = "DEATH_CROSS"
    RELATIVE_STRENGTH_HIGH = "RELATIVE_STRENGTH_HIGH"
    RELATIVE_STRENGTH_LOW = "RELATIVE_STRENGTH_LOW"

    # --- Risk/Portfolio ---
    CONCENTRATION = "CONCENTRATION"
    CORRELATION_HIGH = "CORRELATION_HIGH"
    CORRELATION_LOW = "CORRELATION_LOW"
    LIQUIDITY_LOW = "LIQUIDITY_LOW"
    LIQUIDITY_OK = "LIQUIDITY_OK"
    DRAWDOWN_RISK = "DRAWDOWN_RISK"
    ACCOUNTING_RED_FLAG = "ACCOUNTING_RED_FLAG"
    GOVERNANCE_CONCERN = "GOVERNANCE_CONCERN"
    LEVERAGE_HIGH = "LEVERAGE_HIGH"
    LEVERAGE_OK = "LEVERAGE_OK"
    VOLATILITY_HIGH = "VOLATILITY_HIGH"
    VOLATILITY_LOW = "VOLATILITY_LOW"
    SECTOR_OVERWEIGHT = "SECTOR_OVERWEIGHT"
    SECTOR_UNDERWEIGHT = "SECTOR_UNDERWEIGHT"

    # --- Special Situation ---
    SPINOFF_ANNOUNCED = "SPINOFF_ANNOUNCED"
    MERGER_TARGET = "MERGER_TARGET"
    INSIDER_CLUSTER_BUY = "INSIDER_CLUSTER_BUY"
    INSIDER_CLUSTER_SELL = "INSIDER_CLUSTER_SELL"
    ACTIVIST_INVOLVED = "ACTIVIST_INVOLVED"
    MANAGEMENT_CHANGE = "MANAGEMENT_CHANGE"
    REGULATORY_CHANGE = "REGULATORY_CHANGE"
    PATENT_CATALYST = "PATENT_CATALYST"
    EARNINGS_SURPRISE = "EARNINGS_SURPRISE"
    GUIDANCE_RAISED = "GUIDANCE_RAISED"
    GUIDANCE_LOWERED = "GUIDANCE_LOWERED"

    # --- Decision/Action ---
    BUY_NEW = "BUY_NEW"
    BUY_ADD = "BUY_ADD"
    TRIM = "TRIM"
    SELL_FULL = "SELL_FULL"
    SELL_PARTIAL = "SELL_PARTIAL"
    HOLD = "HOLD"
    HOLD_STRONG = "HOLD_STRONG"
    WATCHLIST_ADD = "WATCHLIST_ADD"
    WATCHLIST_REMOVE = "WATCHLIST_REMOVE"
    WATCHLIST_PROMOTE = "WATCHLIST_PROMOTE"
    REJECT = "REJECT"
    REJECT_HARD = "REJECT_HARD"
    CONFLICT_FLAG = "CONFLICT_FLAG"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    MUNGER_PROCEED = "MUNGER_PROCEED"
    MUNGER_CAUTION = "MUNGER_CAUTION"
    MUNGER_VETO = "MUNGER_VETO"
    NO_ACTION = "NO_ACTION"


@dataclass
class Signal:
    tag: SignalTag
    strength: str  # "strong", "moderate", "weak"
    detail: str = ""


@dataclass
class SignalSet:
    signals: list[Signal] = field(default_factory=list)

    @property
    def tags(self) -> set[SignalTag]:
        return {s.tag for s in self.signals}

    def has(self, tag: SignalTag) -> bool:
        return any(s.tag == tag for s in self.signals)

    def get(self, tag: SignalTag) -> Signal | None:
        for s in self.signals:
            if s.tag == tag:
                return s
        return None


@dataclass
class AgentSignalSet:
    agent_name: str
    model: str
    signals: SignalSet
    confidence: Decimal
    reasoning: str
    target_price: Decimal | None = None
    token_usage: dict | None = None
    latency_ms: int | None = None
