from __future__ import annotations

from investmentology.models.signal import SignalTag

# Category sets — group SignalTag members by category
FUNDAMENTAL_TAGS: frozenset[SignalTag] = frozenset({
    SignalTag.UNDERVALUED, SignalTag.OVERVALUED, SignalTag.FAIRLY_VALUED, SignalTag.DEEP_VALUE,
    SignalTag.MOAT_WIDENING, SignalTag.MOAT_STABLE, SignalTag.MOAT_NARROWING, SignalTag.NO_MOAT,
    SignalTag.EARNINGS_QUALITY_HIGH, SignalTag.EARNINGS_QUALITY_LOW,
    SignalTag.REVENUE_ACCELERATING, SignalTag.REVENUE_DECELERATING,
    SignalTag.MARGIN_EXPANDING, SignalTag.MARGIN_COMPRESSING,
    SignalTag.BALANCE_SHEET_STRONG, SignalTag.BALANCE_SHEET_WEAK,
    SignalTag.DIVIDEND_GROWING, SignalTag.BUYBACK_ACTIVE, SignalTag.MANAGEMENT_ALIGNED,
    SignalTag.MANAGEMENT_MISALIGNED, SignalTag.ROIC_IMPROVING, SignalTag.ROIC_DECLINING,
    SignalTag.CAPITAL_ALLOCATION_EXCELLENT, SignalTag.CAPITAL_ALLOCATION_POOR,
})

MACRO_TAGS: frozenset[SignalTag] = frozenset({
    SignalTag.REGIME_BULL, SignalTag.REGIME_BEAR, SignalTag.REGIME_NEUTRAL, SignalTag.REGIME_TRANSITION,
    SignalTag.SECTOR_ROTATION_INTO, SignalTag.SECTOR_ROTATION_OUT,
    SignalTag.CREDIT_TIGHTENING, SignalTag.CREDIT_EASING,
    SignalTag.RATE_RISING, SignalTag.RATE_FALLING,
    SignalTag.INFLATION_HIGH, SignalTag.INFLATION_LOW,
    SignalTag.DOLLAR_STRONG, SignalTag.DOLLAR_WEAK,
    SignalTag.GEOPOLITICAL_RISK, SignalTag.SUPPLY_CHAIN_DISRUPTION,
    SignalTag.FISCAL_STIMULUS, SignalTag.FISCAL_CONTRACTION,
    SignalTag.LIQUIDITY_ABUNDANT, SignalTag.LIQUIDITY_TIGHT,
    SignalTag.REFLEXIVITY_DETECTED,
    SignalTag.REGIME_TRANSITION_UP, SignalTag.REGIME_TRANSITION_DOWN, SignalTag.REGIME_CHOPPY,
    SignalTag.CYCLE_EARLY, SignalTag.CYCLE_MID, SignalTag.CYCLE_LATE, SignalTag.CYCLE_CONTRACTION,
    SignalTag.RATES_STABLE, SignalTag.MACRO_CATALYST,
})

TECHNICAL_TAGS: frozenset[SignalTag] = frozenset({
    SignalTag.TREND_UPTREND, SignalTag.TREND_DOWNTREND, SignalTag.TREND_SIDEWAYS,
    SignalTag.MOMENTUM_STRONG, SignalTag.MOMENTUM_WEAK, SignalTag.MOMENTUM_DIVERGENCE,
    SignalTag.BREAKOUT_CONFIRMED, SignalTag.BREAKDOWN_CONFIRMED,
    SignalTag.SUPPORT_NEAR, SignalTag.RESISTANCE_NEAR,
    SignalTag.VOLUME_SURGE, SignalTag.VOLUME_DRY, SignalTag.VOLUME_CLIMAX,
    SignalTag.RSI_OVERSOLD, SignalTag.RSI_OVERBOUGHT,
    SignalTag.GOLDEN_CROSS, SignalTag.DEATH_CROSS,
    SignalTag.RELATIVE_STRENGTH_HIGH, SignalTag.RELATIVE_STRENGTH_LOW,
    SignalTag.TREND_REVERSAL_BULLISH, SignalTag.TREND_REVERSAL_BEARISH,
    SignalTag.PATTERN_BULL_FLAG, SignalTag.PATTERN_BASE_FORMING,
})

RISK_TAGS: frozenset[SignalTag] = frozenset({
    SignalTag.CONCENTRATION, SignalTag.CORRELATION_HIGH, SignalTag.CORRELATION_LOW,
    SignalTag.LIQUIDITY_LOW, SignalTag.LIQUIDITY_OK,
    SignalTag.DRAWDOWN_RISK, SignalTag.ACCOUNTING_RED_FLAG, SignalTag.GOVERNANCE_CONCERN,
    SignalTag.LEVERAGE_HIGH, SignalTag.LEVERAGE_OK,
    SignalTag.VOLATILITY_HIGH, SignalTag.VOLATILITY_LOW,
    SignalTag.SECTOR_OVERWEIGHT, SignalTag.SECTOR_UNDERWEIGHT,
    SignalTag.RISK_LITIGATION, SignalTag.RISK_KEY_PERSON, SignalTag.RISK_CUSTOMER_CONCENTRATION,
    SignalTag.PORTFOLIO_OVER_EXPOSED, SignalTag.PORTFOLIO_UNDERWEIGHT_CASH,
})

SPECIAL_TAGS: frozenset[SignalTag] = frozenset({
    SignalTag.SPINOFF_ANNOUNCED, SignalTag.MERGER_TARGET,
    SignalTag.INSIDER_CLUSTER_BUY, SignalTag.INSIDER_CLUSTER_SELL,
    SignalTag.ACTIVIST_INVOLVED, SignalTag.MANAGEMENT_CHANGE, SignalTag.REGULATORY_CHANGE,
    SignalTag.PATENT_CATALYST, SignalTag.EARNINGS_SURPRISE,
    SignalTag.GUIDANCE_RAISED, SignalTag.GUIDANCE_LOWERED,
    SignalTag.SPINOFF_SELLING_PEAK, SignalTag.POST_BANKRUPTCY, SignalTag.RIGHTS_OFFERING,
    SignalTag.INDEX_ADD, SignalTag.INDEX_DROP, SignalTag.CONGRESSIONAL_TRADE,
})

ACTION_TAGS: frozenset[SignalTag] = frozenset({
    SignalTag.BUY_NEW, SignalTag.BUY_ADD, SignalTag.TRIM, SignalTag.SELL_FULL, SignalTag.SELL_PARTIAL,
    SignalTag.HOLD, SignalTag.HOLD_STRONG,
    SignalTag.WATCHLIST_ADD, SignalTag.WATCHLIST_REMOVE, SignalTag.WATCHLIST_PROMOTE,
    SignalTag.REJECT, SignalTag.REJECT_HARD,
    SignalTag.CONFLICT_FLAG, SignalTag.REVIEW_REQUIRED,
    SignalTag.MUNGER_PROCEED, SignalTag.MUNGER_CAUTION, SignalTag.MUNGER_VETO,
    SignalTag.NO_ACTION, SignalTag.MISSED,
    SignalTag.REASON_THESIS_BROKEN, SignalTag.REASON_STOP_LOSS, SignalTag.REASON_TARGET_REACHED,
    SignalTag.REASON_OPPORTUNITY_COST, SignalTag.REASON_REGIME_SHIFT, SignalTag.REASON_REBALANCE,
    SignalTag.REASON_TAX_LOSS, SignalTag.REASON_POSITION_LIMIT, SignalTag.FORCED_SELLING_OVERRIDE,
})

# Cross-cutting tags that all agents may emit.
# During peer-review rounds agents naturally reference other domains' signals,
# so we allow all domain tags as cross-cutting rather than restricting per-agent.
CROSS_CUTTING_TAGS: frozenset[SignalTag] = (
    FUNDAMENTAL_TAGS | MACRO_TAGS | TECHNICAL_TAGS | RISK_TAGS | SPECIAL_TAGS
)

# All valid tags (any domain + actions) — used by agents during peer review
ALL_DOMAIN_TAGS: frozenset[SignalTag] = CROSS_CUTTING_TAGS | ACTION_TAGS

CATEGORY_MAP: dict[str, frozenset[SignalTag]] = {
    "fundamental": FUNDAMENTAL_TAGS,
    "macro": MACRO_TAGS,
    "technical": TECHNICAL_TAGS,
    "risk": RISK_TAGS,
    "special": SPECIAL_TAGS,
    "action": ACTION_TAGS,
}

# Alias mapping: spec-style prefixed names and common LLM hallucinations → code enum values.
# This allows agents returning spec names (e.g. FUNDAMENTAL_UNDERVALUED) or
# near-miss names (e.g. FX_HEADWIND) to resolve to the correct SignalTag.
TAG_ALIASES: dict[str, str] = {
    # Spec prefixed fundamental names
    "FUNDAMENTAL_UNDERVALUED": "UNDERVALUED",
    "FUNDAMENTAL_OVERVALUED": "OVERVALUED",
    "FUNDAMENTAL_FAIR_VALUE": "FAIRLY_VALUED",
    "MOAT_ERODING": "MOAT_NARROWING",
    "BALANCE_SHEET_FORTRESS": "BALANCE_SHEET_STRONG",
    "BALANCE_SHEET_FRAGILE": "BALANCE_SHEET_WEAK",
    "DIVIDEND_ARISTOCRAT": "DIVIDEND_GROWING",
    "BUYBACK_SMART": "BUYBACK_ACTIVE",
    "BUYBACK_DUMB": "CAPITAL_ALLOCATION_POOR",
    # Spec prefixed macro names
    "CREDIT_LOOSE": "CREDIT_EASING",
    "CREDIT_TIGHT": "LIQUIDITY_TIGHT",
    "RATES_RISING_FAST": "RATE_RISING",
    "RATES_FALLING": "RATE_FALLING",
    "FX_TAILWIND": "DOLLAR_WEAK",
    "FX_HEADWIND": "DOLLAR_STRONG",
    "GEOPOLITICAL_RISK_HIGH": "GEOPOLITICAL_RISK",
    "MACRO_CATALYST_PENDING": "MACRO_CATALYST",
    "CYCLE_EARLY_EXPANSION": "CYCLE_EARLY",
    "CYCLE_MID_EXPANSION": "CYCLE_MID",
    "CYCLE_LATE_EXPANSION": "CYCLE_LATE",
    # Spec prefixed technical names
    "MOMENTUM_STRONG_POSITIVE": "MOMENTUM_STRONG",
    "MOMENTUM_STRONG_NEGATIVE": "MOMENTUM_WEAK",
    "MOMENTUM_EXTREME_OVERBOUGHT": "RSI_OVERBOUGHT",
    "MOMENTUM_EXTREME_OVERSOLD": "RSI_OVERSOLD",
    "VOLUME_ACCUMULATION": "VOLUME_SURGE",
    "VOLUME_DISTRIBUTION": "VOLUME_DRY",
    "PATTERN_BREAKOUT": "BREAKOUT_CONFIRMED",
    "PATTERN_BREAKDOWN": "BREAKDOWN_CONFIRMED",
    "SUPPORT_APPROACHING": "SUPPORT_NEAR",
    "RESISTANCE_APPROACHING": "RESISTANCE_NEAR",
    "RELATIVE_STRENGTH_LEADER": "RELATIVE_STRENGTH_HIGH",
    "RELATIVE_STRENGTH_LAGGARD": "RELATIVE_STRENGTH_LOW",
    # Spec prefixed risk names
    "RISK_CONCENTRATION": "CONCENTRATION",
    "RISK_CORRELATION_HIGH": "CORRELATION_HIGH",
    "RISK_LIQUIDITY_LOW": "LIQUIDITY_LOW",
    "RISK_DRAWDOWN_LIMIT": "DRAWDOWN_RISK",
    "RISK_VOLATILITY_SPIKE": "VOLATILITY_HIGH",
    "RISK_LEVERAGE_CONCERN": "LEVERAGE_HIGH",
    "RISK_ACCOUNTING_RED_FLAG": "ACCOUNTING_RED_FLAG",
    "RISK_REGULATORY": "REGULATORY_CHANGE",
    "RISK_SUPPLY_CHAIN": "SUPPLY_CHAIN_DISRUPTION",
    # Spec prefixed special names
    "SPECIAL_SPINOFF_ANNOUNCED": "SPINOFF_ANNOUNCED",
    "SPECIAL_SPINOFF_SELLING_PEAK": "SPINOFF_SELLING_PEAK",
    "SPECIAL_POST_BANKRUPTCY": "POST_BANKRUPTCY",
    "SPECIAL_MERGER_ARB": "MERGER_TARGET",
    "SPECIAL_ACTIVIST_ENTRY": "ACTIVIST_INVOLVED",
    "SPECIAL_RIGHTS_OFFERING": "RIGHTS_OFFERING",
    "SPECIAL_INDEX_ADD": "INDEX_ADD",
    "SPECIAL_INDEX_DROP": "INDEX_DROP",
    "SPECIAL_INSIDER_CLUSTER_BUY": "INSIDER_CLUSTER_BUY",
    "SPECIAL_CONGRESSIONAL_TRADE": "CONGRESSIONAL_TRADE",
    # Spec prefixed action names
    "ACTION_BUY_NEW": "BUY_NEW",
    "ACTION_BUY_ADD": "BUY_ADD",
    "ACTION_SELL_FULL": "SELL_FULL",
    "ACTION_SELL_TRIM": "TRIM",
    "ACTION_HOLD": "HOLD",
    "ACTION_WATCHLIST_ADD": "WATCHLIST_ADD",
    "ACTION_WATCHLIST_GRADUATE": "WATCHLIST_PROMOTE",
    "ACTION_REJECT": "REJECT",
    "ACTION_MISSED": "MISSED",
    "REASON_MUNGER_VETO": "MUNGER_VETO",
    # Common LLM hallucinations → nearest valid tag
    "CORRELATION_RISK": "CORRELATION_HIGH",
    "INSIDER_SELLING": "INSIDER_CLUSTER_SELL",
    "DATA_OPACITY": "ACCOUNTING_RED_FLAG",
    "DATA_INTEGRITY_RISK": "ACCOUNTING_RED_FLAG",
    "COMPLACENCY_RISK": "DRAWDOWN_RISK",
    "FUNDAMENTAL_DETERIORATION": "EARNINGS_QUALITY_LOW",
    "MACRO_RISK": "GEOPOLITICAL_RISK",
    "MACRO_HEADWIND": "GEOPOLITICAL_RISK",
    "VALUATION_EXTREME": "OVERVALUED",
    "MOMENTUM_STALLING": "MOMENTUM_WEAK",
    "REFLEXIVITY_RISK": "REFLEXIVITY_DETECTED",
    "REFLEXIVITY_TRAP": "REFLEXIVITY_DETECTED",
    "CURRENCY_HEADWIND": "DOLLAR_STRONG",
    "CURRENCY_RISK": "DOLLAR_STRONG",
    "VOLUME_EXHAUSTION": "VOLUME_DRY",
    "TECHNICAL_CAUTION": "RESISTANCE_NEAR",
}


def resolve_tag(raw: str) -> str:
    """Resolve a raw tag string through the alias table."""
    return TAG_ALIASES.get(raw, raw)


def get_category(tag: SignalTag) -> str:
    """Return the category name for a signal tag."""
    for name, tags in CATEGORY_MAP.items():
        if tag in tags:
            return name
    return "unknown"


def get_tags_for_category(category: str) -> frozenset[SignalTag]:
    """Return all tags in a category."""
    return CATEGORY_MAP.get(category, frozenset())
